#ifndef ENUMEXEC_H
#define ENUMEXEC_H
enum class Enumerr:int{
    CONNECTIONOK,
    CONNECTIONERROR,
    READINGOK,
    READINGERROR,
    METALOADERROR,
    SAVINGERROR,
    SAVINGOK
};
#endif // ENUMEXEC_H
